sudo: required
services:
  - docker

before_install:
  - docker build -t routbisu/docker-fe -f Dockerfile.dev .

script:
  - docker run -e CI=true routbisu/docker-fe npm run test

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker-react"
  env: "docker-react"
  bucket_name: "elasticbeanstalk-ap-southeast-1-219248317614"
  bucket_path: "docker-react"
  on:
    branch: "master"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
